### PR TITLE
Open RiseMP in Windows Startup

### PR DESCRIPTION
**Pull request by esibruti**
**Details of Changes**
Add details of changes here.
- Added option to open Rise Media Player in Windows Startup

**Validation**
How did you test these changes?
- [ ] Built and ran the app

### CODE REVIEW

**Comment by esibruti** [comment]
@itsWindows11 I need your help. He's not opening. And I need to know how this part is done for him to get the values ​​as it should be

**Comment by esibruti** [comment]
@YourOrdinaryCat Would you mind helping me get this working? It's just that I'm not able to...

**Comment by itsWindows11** [comment]
I'll try to look at this and merge. Thanks for the PR tho. @josephbeattie please don't merge this right now.

Also, please don't mass-ping devs, I or YourOrdinaryCat may be busy at something else.

**Comment by itsWindows11** [comment]
You seem to have forgot the most important thing  which is the app initialization code so that's why it's not starting up. Lemme try to write some code and request review from @YourOrdinaryCat if possible.

**Comment by itsWindows11** [comment]
Hey @esibruti, It needs to be enabled from Task Manager for it to work, I also made some changes and I will commit it rn.

**Review by itsWindows11 — APPROVED** [review]
As of now, I approved this PR but its not fully ready to be merged yet.

**Comment by esibruti** [comment]
> I'll try to look at this and merge. Thanks for the PR tho. @josephbeattie please don't merge this right now.
> 
> Also, please don't mass-ping devs, I or YourOrdinaryCat may be busy at something else.

It was just to make sure they saw this pr. sorry

**Comment by esibruti** [comment]
> As of now, I approved this PR but its not fully ready to be merged yet. 

Okay, if I need some modification, I can do it. I'm not sure but I think it has to be synchronized with the last changes made.

**Comment by itsWindows11** [comment]
> > As of now, I approved this PR but its not fully ready to be merged yet.
> 
> Okay, if I need some modification, I can do it. I'm not sure but I think it has to be synchronized with the last changes made.

yeah, your branch needs to be updated, also I have to request a review from other devs before merging.

**Comment by itsWindows11** [comment]
@esibruti can you go to your branch on github and sync it with the changes in the main branch here?

**Comment by esibruti** [comment]
@itsWindows11 done

**Comment by itsWindows11** [comment]
good

**Pull request merged**
