### PR TITLE
Basic video functionality added to PlaylistViewModel

### PR DESCRIPTION
**Pull request by isaiahcabugos**
**Resolved / Related Issues**
- Related issue #96 

**Details of Changes**
Notable changes confined to PlaylistViewModel.cs
Added public properties: 
- `ObservableCollection<VideoViewModel> _Videos_ `
- `int VideosCount`

Added public async methods: 
- `AddVideoAsync(VideoViewModel video)`
- `RemoveVideoAsync(VideoViewModel video)`
- `AddVideosAsync(IEnumerable<VideoViewModel> videos)`
- `RemoveVideosAsync(List<VideoViewModel> videos)`

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Notable**
Attempted fixing editing functionality in playlists. Was not successful. Any residual changes within PlaylistSongsPropertiesPage.xaml.cs was from deleting debugging/commented code.

### CODE REVIEW

**Comment by josephbeattie** [comment]
I’m going to keep this PR open for now while we ensure music playlists are stable in their current form :)

**Review by itsWindows11 — CHANGES_REQUESTED** [review]
Please add the list to the playlist details page, this seems to be code only.

**Comment by isaiahcabugos** [comment]
> Please add the list to the playlist details page, this seems to be code only.

Apologies, I don't get what you mean... Is there a playlist details page where I can add the list of properties and functions that I pushed? Or do you just mean that I should add a comment to the issue #96 page? 

Regardless, I'll continue to debug playlist editing. I'm currently rather confused with the invalid cast error that keeps showing up when you click on any of the buttons that are supposed to edit the playlist.

**Comment by josephbeattie** [comment]
PlaylistDetailsPage.xaml displays the songs in a listview. You need to add videos to that list :)

**Comment by isaiahcabugos** [comment]
Closing for now. I am unsure when next I will be able to work on this, and there are many features which I still need to add to make this PR substantial.

**Pull request closed without merging**
