### PR TITLE
Added file browser control

### PR DESCRIPTION
**Pull request by d2dyno1**

### CODE REVIEW

**Comment by yourordinarycat** [comment]
Hello there, I've been taking a look at the code, sorry for the delay on the comment. I think it would help if you spread the code a little across the different projects - stuff like ViewModels could be moved to the `Rise.Data` project for example. I think messages, services, and file explorer views would fit in the `Rise.Storage` project you created as well.

This is mostly done to split up the project more nicely, and compile times in UWP C# projects go way up if a single project has a lot of stuff, specially when it comes to XAML (bug in VS that never got fixed *shrugs*). Some extra comments:

- In [App.xaml.cs](https://github.com/Rise-Software/Rise-Media-Player/pull/167/files#diff-52e679e9bb66461829295b029652379c287337918316e5df4930f60ef6c6d40c), you have `FileBrowserPageViewModel` with a public setter. Please make the setter private.
- `BreadcrumbItemViewModel` would fit more nicely in the Models project, as a model (that is, just name it Breadcrumb or something). ViewModels are mostly there to wrap models with property change notifications and stuff the view may need, and because you don't seem to need those, naming it ViewModel is a little misleading. This also applies to stuff like `FileBrowserHomePageViewModel`.
- There's `FileBrowserHomePage` which, correct me if I'm wrong, but it seems to be empty? If it isn't being used, remove it.

Other than that, stuff looks nice. Thanks for your contribution! Tell me if you need help with anything or have any questions.

**Comment by d2dyno1** [comment]
Hi @YourOrdinaryCat!
Sorry for late reply, but I got tied up in school 🤷
Moving ViewModels to `Rise.Data` would be out of scope for this PR as it'd require some additional changes however, I made that easy by not referencing any UI namespaces.

 `Rise.Storage` was created to provide abstractions to be consumed by both frontend and backend projects (RiseMP doesn't currently support backend and frontend projects separation though). In regards about the `IStorageService` -- it's my personal preference to put the service in the backend instead of `Rise.Storage` since it shouldn't need to use it.

I'm not sure if `BreadcrumbItemViewModel` should be a Model, its properties are bound to the UI so my reasoning was to make it a View-Model.

Some pages are empty but will be implemented later.

**Comment by yourordinarycat** [comment]
I see, that's fair. I too have been tied up by studies lately.

Everything seems good, thanks for the explanation. Do tag me whenever you think the PR can be merged.

**Comment by itsWindows11** [comment]
Any news regarding the file browser?

**Comment by d2dyno1** [comment]
Hi! Currently I'm waiting for @josephbeattie to do the xaml part 👀 

@josephbeattie How's progress on that?

**Comment by itsWindows11** [comment]
@d2dyno1 please resolve the conflicts.

@josephbeattie told me he won't work on the UI.

**Pull request closed without merging**
