### PR TITLE
Feature/personalized thumbnail albums

### PR DESCRIPTION
**Pull request by Orick08**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related #37 

**Details of Changes**
- Added the possibility of change the album thumbnail in the songs view via the properties window.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots / Videos (optional)**
image
image
image

### CODE REVIEW

**Review by itsWindows11 — COMMENTED** [review]
Do changes get saved to the database? I mean, when restarting the app does it persist? If so I might merge this as it looks good.

**Comment by Orick08** [comment]
> Do changes get saved to the database? I mean, when restarting the app does it persist? If so I might merge this as it looks good.

I have troubles with this. Not only the thumbnail not persist, but all the song properties don't save persistently

**Comment by itsWindows11** [comment]
> > Do changes get saved to the database? I mean, when restarting the app does it persist? If so I might merge this as it looks good.
> 
> I have troubles with this. Not only the thumbnail not persist, but all the song properties don't save persistently

Here comes the bad things, well I can't merge this until it's fixed.

**Review by itsWindows11 — APPROVED** [review]
I managed to solve the issue by the way, now lemme merge this.

**Pull request merged**
