### PR TITLE
Code Cleaning

### PR DESCRIPTION
**Pull request by Taiizor**

### CODE REVIEW

**Comment by josephbeattie** [comment]
Please submit a description. Write in the comments what you have changed :) and how it improves optimisation.

**Comment by josephbeattie** [comment]
Any reason this was closed?

**Comment by Taiizor** [comment]
> Any reason this was closed?

Yup. I will do localization for Turkish language. I will open a PR again.

**Comment by josephbeattie** [comment]
Oh cool! Please contact me via Discord if you have that :)

**Comment by Taiizor** [comment]
Ofc. My username Taiizor#6094

**Pull request closed without merging**
