### PR TITLE
Terms and Conditions icon

### PR DESCRIPTION
**Pull request by esibruti**
Before:

image

After:

image

### CODE REVIEW

**Review by itsWindows11 — CHANGES_REQUESTED** [review]
Looks good! but one small suggestion:
image
image
I assume using a book or a document icon for this would be better.

**Comment by itsWindows11** [comment]
What Windows version are you on? On Windows 11 it works fine here.
image

**Comment by esibruti** [comment]
> What Windows version are you on? On Windows 11 it works fine here. image

Windows 10 21h1
It must be that it is an incompatible icon on windows 10

**Comment by esibruti** [comment]
@itsWindows11 I already found out, if you go to this link ([https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font]()), you can see the windows 10 glyphys. That glyphy doesn't exist in windows 10.

**Pull request closed without merging**
