### PR TITLE
Improve indexing (again)

### PR DESCRIPTION
**Pull request by yourordinarycat**
**Resolved / Related Issues**
#40 and similar should be improved or fixed (be it now or in the near future) thanks to this.

**Details of Changes**
The current `IndexingHelper` class is annoying to use and maintain. It contains an excessive amount of boilerplate that can be removed, unused events due to their lack of reliability, and it needs to be instantiated for (mostly) no good reason.
- C# 8 introduced [async streams](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/async-streams), so passing a Task to process every `StorageFile` isn't needed, since we can just [yield](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield).
- Cancellation support is not necessary due to the outlined above. We can easily break out of a loop when using `IAsyncEnumerable`, so there's no need to complicate things even more by adding cancellation tokens as function arguments. `ICancellableTask` in general isn't pleasant to work with, but that's outside of this PR's scope.
- The `StorageExtensions` class would be merged into `IndexingHelpers`, there's no need to have a second static class with only two functions.

**Validation**
Currently the changes are not tested. However, I will be updating this PR with comments and progress reports when necessary.

**Screenshots / Videos (optional)**
Read above.

### CODE REVIEW

**Comment by yourordinarycat** [comment]
Big improvements have already been made! Code looks much better. Now it's a matter of updating everything and testing. Some code is tied to the `Finished` event, but this should be easy to implement in the `MainViewModel`.

**Comment by yourordinarycat** [comment]
The app can't be deployed from [5a1938f](https://github.com/Rise-Software/Rise-Media-Player/pull/129/commits/5a1938fe52243ffa02e2a8a5d89c0f73797574b9). All the references to the original class must be removed first.

**Comment by yourordinarycat** [comment]
It is now possible to deploy the app.

**Comment by josephbeattie** [comment]
Hey question, any reason this is a PR and you’re not committing directly?

**Comment by yourordinarycat** [comment]
Didn't want to break anyone's fork/clone/whatever, plus I wanted to have this a bit more documented :b

**Comment by josephbeattie** [comment]
Ah okay. So happy to see your name on GitHub again! 😊

**Comment by yourordinarycat** [comment]
The events have been implemented. There are new event args for when indexing finishes, which contain the amount of videos and songs added. @josephbeattie you might find that useful ;)

**Comment by yourordinarycat** [comment]
This PR mostly contains improvements to codebase maintainability - actual indexing improvements (performance, reliability) will come later more easily as a result, but for now, I'm merging this in its current state. Next goal would be improvements to the DB system, which may allow for background change tracking at a later date.

**Pull request merged**
