### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by d2dyno1**
This PR addresses some bugs in the current release.

Issues fixed:
- Clicking the navigation view no longer causes a crash
- Reordering items on the sidebar now works correctly
- Removing section from the sidebar no longer causes a crash
- (apparently fixed) Switching icon styles now works correctly

### CODE REVIEW

**Comment by itsWindows11** [comment]
Does the navigation view automatically collapse when the width is smaller than 800? Looking at the code I think you removed that

**Comment by d2dyno1** [comment]
@itsWindows11 It still does. I just hit Ctrl+S with [XamlStyler](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022) and it automatically formatted the xaml. I can recommend this extension, it helps to make xaml clearer and more consistent.

**Comment by itsWindows11** [comment]
> @itsWindows11 It still does. I just hit Ctrl+S with [XamlStyler](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022) and it automatically formatted the xaml. I can recommend this extension, it helps to make xaml clearer and more consistent.

oh, i see, i'll try to review this soon.

**Review by itsWindows11 — APPROVED** [review]
Thank you! you also fixed that remove whole section bug!

**Pull request merged**
