### PR TITLE
Back button

### PR DESCRIPTION
**Pull request by esibruti**
**Details of Changes**
Add details of changes here.
- Added back button in settings.
It is not working properly. I need someone's help

### CODE REVIEW

**Comment by itsWindows11** [comment]
Sorry, but it's being already worked on.

**Comment by esibruti** [comment]
@itsWindows11 But that's in the settings. It was Discy who told me to do it

**Comment by itsWindows11** [comment]
> @itsWindows11 But that's in the settings. It was Discy who told me to do it

Still, its already being worked on, this PR broke most of the back button's functionality (and the animation) and you're basically locked in the page until you restart the app.

**Comment by esibruti** [comment]
> > @itsWindows11 But that's in the settings. It was Discy who told me to do it
> 
> Still, its already being worked on, this PR broke most of the back button's functionality (and the animation) and you're basically locked in the page until you restart the app.

Ok, no problem

**Pull request closed without merging**
