### PR TITLE
Now Playing Bar - AutoHide

### PR DESCRIPTION
**Pull request by esibruti**
Now Playing Bar - AutoHide

### CODE REVIEW

**Review by itsWindows11 — APPROVED** [review]
Thanks, looks good. I'll commit something to this quick as the now playing bar should be visible when a video is played, too!

**Comment by esibruti** [comment]
@itsWindows11 I need to clear the code, give me a few minutes
it won't take long

**Comment by esibruti** [comment]
@itsWindows11 its ready

**Comment by itsWindows11** [comment]
okay

**Pull request merged**
