### PR TITLE
MVVM

### PR DESCRIPTION
**Pull request by esibruti**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Related #160 
ONLY TESTING

**Details of Changes**
Add details of changes here.

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots / Videos (optional)**
Add screenshots and/or videos here.

### CODE REVIEW

**Comment by itsWindows11** [comment]
As I said in our DMs, I will work on it, also there seems to be too many breaking changes and I want to ensure that existing branches here are compatible without doing way too much work, so I'll close this, sorry for the inconvenience.

**Comment by esibruti** [comment]
> As I said in our DMs, I will work on it, also there seems to be too many breaking changes and I want to ensure that existing branches here are compatible without doing way too much work, so I'll close this, sorry for the inconvenience.

@itsWindows11 No problem, I know we talked about it and you were the one who was going to take care of it. I was just doing a test of what it would be like if I did that, it was just with that intention of testing

**Comment by itsWindows11** [comment]
> > As I said in our DMs, I will work on it, also there seems to be too many breaking changes and I want to ensure that existing branches here are compatible without doing way too much work, so I'll close this, sorry for the inconvenience.
> 
> @itsWindows11 No problem, I know we talked about it and you were the one who was going to take care of it. I was just doing a test of what it would be like if I did that, it was just with that intention of testing

I know, just don't want some collaborator to accidentally click on the merge button and break everything we did (for example in #159)

**Comment by esibruti** [comment]
> > > As I said in our DMs, I will work on it, also there seems to be too many breaking changes and I want to ensure that existing branches here are compatible without doing way too much work, so I'll close this, sorry for the inconvenience.
> > 
> > @itsWindows11 No problem, I know we talked about it and you were the one who was going to take care of it. I was just doing a test of what it would be like if I did that, it was just with that intention of testing
> 
> I know, just don't want some collaborator to accidentally click on the merge button and break everything we did (for example in #159)

I don't even want to imagine the headache that would be but yes, I understand that. No problem.

**Pull request closed without merging**
