### PR TITLE
Bug Report, Pull Request and Feature Request templates

### PR DESCRIPTION
**Pull request by esibruti**
Three templates were created.

The Pull Request template will help the contributor to clearly and accurately indicate the changes he will make with the PR. You must ALWAYS indicate which issue is related or indicate the issue that will be closed after the PR is approved.

The Bug Report template will be for the contributor to indicate clearer and more precise information about the problem they are having with Rise Media Player, indicating the information of the bug presented with screenshots, videos, crash window (log), version of Rise Media Player and the Windows version.

Finally, the Feature Request template will help the contributor to indicate clearly and precisely what functionality they would like to see in Rise Media Player, indicating some information.

Inspired by the templates on Files Community
Files, don't be mad at me😥

### CODE REVIEW

**Comment by itsWindows11** [comment]
Next time, please make a branch for a specific PR so that the commit list is clean and it will be clear what's new. also don't use the `dev` branch for pull requests.

**Comment by esibruti** [comment]
> Next time, please make a branch for a specific PR so that the commit list is clean and it will be clear what's new.

@itsWindows11 You're right, in fact, I should have done that. sorry

But do you want me to delete everything and do it again?

**Comment by itsWindows11** [comment]
> > Next time, please make a branch for a specific PR so that the commit list is clean and it will be clear what's new.
> 
> @itsWindows11 You're right, in fact, I should have done that. sorry

there's no problem, I'm just trying to recommend something so that it's easier for us to review :)

**Comment by esibruti** [comment]
> > > Next time, please make a branch for a specific PR so that the commit list is clean and it will be clear what's new.
> > 
> > @itsWindows11 You're right, in fact, I should have done that. sorry
> 
> there's no problem, I'm just trying to recommend something so that it's easier for us to review :)

Ahh ok ok I get it, yes in fact I should have done it. It happens to be something I didn't remember to do.

**Pull request merged**
