### PR TITLE
Improve the process of inserting changes into the database

### PR DESCRIPTION
**Pull request by yourordinarycat**
**Resolved / Related Issues**
This begins work on #131.

**Details of Changes**
In #131, this is expected to resolve item 2 (instead of inserting to the DB and the media collections at the same time, insert everything into DB first, and when we're done, get data from there) and possibly item 1 (Implement background change tracking). This round of changes is gonna be pretty big, so it's gonna live in a PR and likely stay here for a while.

**Validation**
Not tested yet.

**Screenshots / Videos (optional)**
None yet, these are backend changes.

### CODE REVIEW

**Comment by josephbeattie** [comment]
hey cat, this looks promising! can’t wait to see what comes next! Also, there is an issue where the app hangs on startup before the scanning teachingtip or any ui appears. Are you aware of this and trying to fix it?

**Comment by yourordinarycat** [comment]
I'm aware of that, I'm guessing some operations are blocking the UI thread (probably settings related). I'm gonna work on lifecycle management as well, so that'll definitely be getting improvements!

**Comment by josephbeattie** [comment]
Ah thanks for keeping me in the know! Try and have a look at this ASAP if you can (want this to be fixed in the next day or two if possible)

**Comment by yourordinarycat** [comment]
WHY DID IT MERGE

**Pull request merged**
